#!/bin/bash
### BEGIN INIT INFO
# Provides:		lab_server
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start:	2  3  4  5
# Default-Stop:		0  1  6
# Short-Description:	Labrest daemon
### END INIT INFO

DAEMON_PATH="/opt/labrest"

DAEMON=./labrest_server
DAEMONOPTS=""

NAME=lab_server
DESC="Server for Lab Resource Tracker"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/var/log/$NAME.log

case "$1" in
start)
        RUNSRV=1
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
	        RUNSRV=1
            else
		RUNSRV=0
            fi
        else
	    RUNSRV=1
        fi
 	if [ $RUNSRV -eq 1 ]; then
	    printf "%-50s" "Starting $NAME..."
	    cd $DAEMON_PATH
 	    PID=`sudo -u labrestd $DAEMON $DAEMONOPTS > $LOGFILE 2>&1 & echo $!`
	    #echo "Saving PID" $PID " to " $PIDFILE
            if [ -z $PID ]; then
                printf "%s\n" "Fail"
            else
                echo $PID > $PIDFILE
                printf "%s\n" "Ok"
            fi
	else
	    echo "Already running"
	fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
